# Generated by Django 6.0.1 on 2026-01-29 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Account Name (e.g. Cash, Revenue, Inventory, COGS)', max_length=200, unique=True)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount: positive/negative based on account type', max_digits=15)),
                ('reference_type', models.CharField(choices=[('SALE', 'sale'), ('REFUND', 'refund'), ('ADJUSTMENT', 'adjustment')], db_index=True, max_length=20)),
                ('reference_id', models.UUIDField(db_index=True, help_text='Links to Sale, Refund, or other source transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.account')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'ledger_entry',
                'indexes': [models.Index(fields=['account', 'created_at'], name='ledger_entr_account_b86ea8_idx'), models.Index(fields=['reference_type', 'reference_id'], name='ledger_entr_referen_35b585_idx')],
            },
        ),
    ]
