# Generated by Django 6.0.1 on 2026-01-26 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('location', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                 'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - Unique Product Identifier', max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=15)),
                ('track_stock', models.BooleanField(default=True, help_text='False for services or non-tracked items')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                 'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('SALE', 'Sale'), ('REFUND', 'Refund')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Signed quantity: positive for IN, negative for OUT', max_digits=15)),
                ('reference_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('MANUAL', 'Manual')], max_length=20)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, help_text='Links to sale, purchase, or other source transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movement',
                'indexes': [models.Index(fields=['product', 'warehouse'], name='stock_movem_product_eeb7da_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_55f8d1_idx'), models.Index(fields=['created_by', 'created_at'], name='stock_movem_created_9a6821_idx')],
            },
        ),
    ]
