# Generated by Django 6.0.1 on 2026-01-29 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VOID', 'Void')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, help_text='Model name (e.g., Sale, Product, User)', max_length=100)),
                ('entity_id', models.UUIDField(db_index=True, help_text='Primary Key for affected entity')),
                ('before_state', models.JSONField(blank=True, help_text='JSON snapshot before the operation', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='JSON snapshot after the operation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'), models.Index(fields=['user', 'created_at'], name='audit_log_user_id_3b54b4_idx'), models.Index(fields=['action', 'created_at'], name='audit_log_action_97df64_idx')],
            },
        ),
    ]
